#include "dcmi.h"
#include "ov7670.h"
//#include "string.h"
//#include "sys_cfg.h"

uint8_t ov_frame=0;  						//֡��
uint32_t datanum=0;
uint32_t HSYNC=0;
uint32_t VSYNC=0;
//DCMI_InitTypeDef DCMI_InitStructure;
uint8_t ov_rev_ok = 0;

void DCMI_DMA_Init(uint32_t DMA_Memory0BaseAddr,uint16_t DMA_BufferSize){
	SET_BIT(RCC_BASE + RCC_AHB1ENR_OFFSET, DMA2EN);
	DMA2_Steam1_DeInit();
	while(DMA2_Steam1_GetCmdStatus() == 1);
	DMA2_Steam1_Init(DMA_Memory0BaseAddr, DMA_BufferSize);
	/*
	DMA_InitTypeDef  DMA_InitStructure;
	NVIC_InitTypeDef NVIC_InitStructure;

	RCC_AHB1PeriphClockCmd(RCC_AHB1Periph_DMA2,ENABLE);//DMA2ʱ��ʹ��
	DMA_DeInit(DMA2_Stream1);
	while (DMA_GetCmdStatus(DMA2_Stream1) != DISABLE){}//�ȴ�DMA2_Stream1������

	DMA_InitStructure.DMA_Channel = DMA_Channel_1;  //ͨ��1 DCMIͨ��
	DMA_InitStructure.DMA_PeripheralBaseAddr = (uint32_t)&DCMI->DR; ;//������ַΪ:DCMI->DR
	DMA_InitStructure.DMA_Memory0BaseAddr = (uint32_t)DMA_Memory0BaseAddr;//DMA �洢��0��ַ
	DMA_InitStructure.DMA_DIR = DMA_DIR_PeripheralToMemory;//���赽�洢��ģʽ
	DMA_InitStructure.DMA_BufferSize = DMA_BufferSize;//���ݴ�����
	DMA_InitStructure.DMA_PeripheralInc = DMA_PeripheralInc_Disable;//����������ģʽ
	DMA_InitStructure.DMA_MemoryInc = DMA_MemoryInc;//�洢������ģʽ
	DMA_InitStructure.DMA_PeripheralDataSize = DMA_PeripheralDataSize_Word;//�������ݳ���:32λ
	DMA_InitStructure.DMA_MemoryDataSize = DMA_MemoryDataSize;//�洢�����ݳ���
	DMA_InitStructure.DMA_Mode = DMA_Mode_Circular;// ʹ��ѭ��ģʽ  DMA_Mode_Normal
	DMA_InitStructure.DMA_Priority = DMA_Priority_High;//�����ȼ�
	DMA_InitStructure.DMA_FIFOMode = DMA_FIFOMode_Enable; //FIFOģʽ
	DMA_InitStructure.DMA_FIFOThreshold = DMA_FIFOThreshold_Full;//ʹ��ȫFIFO
	DMA_InitStructure.DMA_MemoryBurst = DMA_MemoryBurst_Single;//����ͻ�����δ���
	DMA_InitStructure.DMA_PeripheralBurst = DMA_PeripheralBurst_Single;//�洢��ͻ�����δ���
	DMA_Init(DMA2_Stream1, &DMA_InitStructure);//��ʼ��DMA Stream

	DMA_ITConfig(DMA2_Stream1,DMA_IT_TC,ENABLE);

	NVIC_InitStructure.NVIC_IRQChannel=	DMA2_Stream1_IRQn;
	NVIC_InitStructure.NVIC_IRQChannelPreemptionPriority=0;
	NVIC_InitStructure.NVIC_IRQChannelSubPriority=0;
	NVIC_InitStructure.NVIC_IRQChannelCmd=ENABLE;
	NVIC_Init(&NVIC_InitStructure);	//����ָ���Ĳ�����ʼ��VIC�Ĵ�����
	*/
	SET_BIT(NVIC_ISER_BASE + NVIC_ISERn_OFFSET(1), 25); //IRQ57
}

void dma2_stream1_handler(void){
	uint32_t tmp_DMA_TCIF1 = READ_BIT(DMA2_BASE + DMA_LISR_OFFSET, DMA_TCIF1);
	if(tmp_DMA_TCIF1)//DMA2_Steam1,�������ɱ�־
	{
		CLEAR_BIT(DMA2_BASE + DMA_S1CR_OFFSET, DMA_EN_BIT);
		SET_BIT(DMA2_BASE + DMA_LIFCR_OFFSET, DMA_CTCIF1);
		/*
		DMA_Cmd(DMA2_Stream1, DISABLE);
		DMA_ClearFlag(DMA2_Stream1,DMA_FLAG_TCIF1);//�������������ж�
		*/
		printf("ov_rev_ok, %u\r\n", (unsigned int)datanum);
		ov_rev_ok= 1;
		datanum++;
	}
}

void My_DCMI_Init(void){
	SET_BIT(RCC_BASE + RCC_AHB1ENR_OFFSET, GPIO_EN_BIT(GPIO_PORTA));
	SET_BIT(RCC_BASE + RCC_AHB1ENR_OFFSET, GPIO_EN_BIT(GPIO_PORTB));
	SET_BIT(RCC_BASE + RCC_AHB1ENR_OFFSET, GPIO_EN_BIT(GPIO_PORTC));
	SET_BIT(RCC_BASE + RCC_AHB1ENR_OFFSET, GPIO_EN_BIT(GPIO_PORTE));

	SET_BIT(RCC_BASE + RCC_AHB2ENR_OFFSET, DCMIEN);

	SET_BIT(GPIO_BASE(GPIO_PORTA) + GPIOx_MODER_OFFSET, MODERy_1_BIT(4));							//MODER => 10
	CLEAR_BIT(GPIO_BASE(GPIO_PORTA) + GPIOx_MODER_OFFSET, MODERy_0_BIT(4));
	CLEAR_BIT(GPIO_BASE(GPIO_PORTA) + GPIOx_OTYPER_OFFSET, OTy_BIT(4));								//OT => 0
	SET_BIT(GPIO_BASE(GPIO_PORTA) + GPIOx_OSPEEDR_OFFSET, OSPEEDRy_1_BIT(4));						//OSPEEDR => 10
	CLEAR_BIT(GPIO_BASE(GPIO_PORTA) + GPIOx_OSPEEDR_OFFSET, OSPEEDRy_0_BIT(4));
	CLEAR_BIT(GPIO_BASE(GPIO_PORTA) + GPIOx_PUPDR_OFFSET, PUPDRy_1_BIT(4));							//PUPDR = 00 => No pull-up, pull-down
	SET_BIT(GPIO_BASE(GPIO_PORTA) + GPIOx_PUPDR_OFFSET, PUPDRy_0_BIT(4));
	WRITE_BITS(GPIO_BASE(GPIO_PORTA) + GPIOx_AFRL_OFFSET, AFRLy_3_BIT(4), AFRLy_0_BIT(4), 13);		//AF sel	dcmi	13

	SET_BIT(GPIO_BASE(GPIO_PORTA) + GPIOx_MODER_OFFSET, MODERy_1_BIT(6));							//MODER => 10
	CLEAR_BIT(GPIO_BASE(GPIO_PORTA) + GPIOx_MODER_OFFSET, MODERy_0_BIT(6));
	CLEAR_BIT(GPIO_BASE(GPIO_PORTA) + GPIOx_OTYPER_OFFSET, OTy_BIT(6));								//OT => 0
	SET_BIT(GPIO_BASE(GPIO_PORTA) + GPIOx_OSPEEDR_OFFSET, OSPEEDRy_1_BIT(6));						//OSPEEDR => 10
	CLEAR_BIT(GPIO_BASE(GPIO_PORTA) + GPIOx_OSPEEDR_OFFSET, OSPEEDRy_0_BIT(6));
	CLEAR_BIT(GPIO_BASE(GPIO_PORTA) + GPIOx_PUPDR_OFFSET, PUPDRy_1_BIT(6));							//PUPDR = 00 => No pull-up, pull-down
	SET_BIT(GPIO_BASE(GPIO_PORTA) + GPIOx_PUPDR_OFFSET, PUPDRy_0_BIT(6));
	WRITE_BITS(GPIO_BASE(GPIO_PORTA) + GPIOx_AFRL_OFFSET, AFRLy_3_BIT(6), AFRLy_0_BIT(6), 13);		//AF sel	dcmi	13

	SET_BIT(GPIO_BASE(GPIO_PORTB) + GPIOx_MODER_OFFSET, MODERy_1_BIT(6));							//MODER => 10
	CLEAR_BIT(GPIO_BASE(GPIO_PORTB) + GPIOx_MODER_OFFSET, MODERy_0_BIT(6));
	CLEAR_BIT(GPIO_BASE(GPIO_PORTB) + GPIOx_OTYPER_OFFSET, OTy_BIT(6));								//OT => 0
	SET_BIT(GPIO_BASE(GPIO_PORTB) + GPIOx_OSPEEDR_OFFSET, OSPEEDRy_1_BIT(6));						//OSPEEDR => 10
	CLEAR_BIT(GPIO_BASE(GPIO_PORTB) + GPIOx_OSPEEDR_OFFSET, OSPEEDRy_0_BIT(6));
	CLEAR_BIT(GPIO_BASE(GPIO_PORTB) + GPIOx_PUPDR_OFFSET, PUPDRy_1_BIT(6));							//PUPDR = 00 => No pull-up, pull-down
	SET_BIT(GPIO_BASE(GPIO_PORTB) + GPIOx_PUPDR_OFFSET, PUPDRy_0_BIT(6));
	WRITE_BITS(GPIO_BASE(GPIO_PORTB) + GPIOx_AFRL_OFFSET, AFRLy_3_BIT(6), AFRLy_0_BIT(6), 13);		//AF sel	dcmi	13

	SET_BIT(GPIO_BASE(GPIO_PORTB) + GPIOx_MODER_OFFSET, MODERy_1_BIT(7));							//MODER => 10
	CLEAR_BIT(GPIO_BASE(GPIO_PORTB) + GPIOx_MODER_OFFSET, MODERy_0_BIT(7));
	CLEAR_BIT(GPIO_BASE(GPIO_PORTB) + GPIOx_OTYPER_OFFSET, OTy_BIT(7));								//OT => 0
	SET_BIT(GPIO_BASE(GPIO_PORTB) + GPIOx_OSPEEDR_OFFSET, OSPEEDRy_1_BIT(7));						//OSPEEDR => 10
	CLEAR_BIT(GPIO_BASE(GPIO_PORTB) + GPIOx_OSPEEDR_OFFSET, OSPEEDRy_0_BIT(7));
	CLEAR_BIT(GPIO_BASE(GPIO_PORTB) + GPIOx_PUPDR_OFFSET, PUPDRy_1_BIT(7));							//PUPDR = 00 => No pull-up, pull-down
	SET_BIT(GPIO_BASE(GPIO_PORTB) + GPIOx_PUPDR_OFFSET, PUPDRy_0_BIT(7));
	WRITE_BITS(GPIO_BASE(GPIO_PORTB) + GPIOx_AFRL_OFFSET, AFRLy_3_BIT(7), AFRLy_0_BIT(7), 13);		//AF sel	dcmi	13

	SET_BIT(GPIO_BASE(GPIO_PORTC) + GPIOx_MODER_OFFSET, MODERy_1_BIT(6));							//MODER => 10
	CLEAR_BIT(GPIO_BASE(GPIO_PORTC) + GPIOx_MODER_OFFSET, MODERy_0_BIT(6));
	CLEAR_BIT(GPIO_BASE(GPIO_PORTC) + GPIOx_OTYPER_OFFSET, OTy_BIT(6));								//OT => 0
	SET_BIT(GPIO_BASE(GPIO_PORTC) + GPIOx_OSPEEDR_OFFSET, OSPEEDRy_1_BIT(6));						//OSPEEDR => 10
	CLEAR_BIT(GPIO_BASE(GPIO_PORTC) + GPIOx_OSPEEDR_OFFSET, OSPEEDRy_0_BIT(6));
	CLEAR_BIT(GPIO_BASE(GPIO_PORTC) + GPIOx_PUPDR_OFFSET, PUPDRy_1_BIT(6));							//PUPDR = 00 => No pull-up, pull-down
	SET_BIT(GPIO_BASE(GPIO_PORTC) + GPIOx_PUPDR_OFFSET, PUPDRy_0_BIT(6));
	WRITE_BITS(GPIO_BASE(GPIO_PORTC) + GPIOx_AFRL_OFFSET, AFRLy_3_BIT(6), AFRLy_0_BIT(6), 13);		//AF sel	dcmi	13

	SET_BIT(GPIO_BASE(GPIO_PORTC) + GPIOx_MODER_OFFSET, MODERy_1_BIT(7));							//MODER => 10
	CLEAR_BIT(GPIO_BASE(GPIO_PORTC) + GPIOx_MODER_OFFSET, MODERy_0_BIT(7));
	CLEAR_BIT(GPIO_BASE(GPIO_PORTC) + GPIOx_OTYPER_OFFSET, OTy_BIT(7));								//OT => 0
	SET_BIT(GPIO_BASE(GPIO_PORTC) + GPIOx_OSPEEDR_OFFSET, OSPEEDRy_1_BIT(7));						//OSPEEDR => 10
	CLEAR_BIT(GPIO_BASE(GPIO_PORTC) + GPIOx_OSPEEDR_OFFSET, OSPEEDRy_0_BIT(7));
	CLEAR_BIT(GPIO_BASE(GPIO_PORTC) + GPIOx_PUPDR_OFFSET, PUPDRy_1_BIT(7));							//PUPDR = 00 => No pull-up, pull-down
	SET_BIT(GPIO_BASE(GPIO_PORTC) + GPIOx_PUPDR_OFFSET, PUPDRy_0_BIT(7));
	WRITE_BITS(GPIO_BASE(GPIO_PORTC) + GPIOx_AFRL_OFFSET, AFRLy_3_BIT(7), AFRLy_0_BIT(7), 13);		//AF sel	dcmi	13

	SET_BIT(GPIO_BASE(GPIO_PORTC) + GPIOx_MODER_OFFSET, MODERy_1_BIT(8));							//MODER => 10
	CLEAR_BIT(GPIO_BASE(GPIO_PORTC) + GPIOx_MODER_OFFSET, MODERy_0_BIT(8));
	CLEAR_BIT(GPIO_BASE(GPIO_PORTC) + GPIOx_OTYPER_OFFSET, OTy_BIT(8));								//OT => 0
	SET_BIT(GPIO_BASE(GPIO_PORTC) + GPIOx_OSPEEDR_OFFSET, OSPEEDRy_1_BIT(8));						//OSPEEDR => 10
	CLEAR_BIT(GPIO_BASE(GPIO_PORTC) + GPIOx_OSPEEDR_OFFSET, OSPEEDRy_0_BIT(8));
	CLEAR_BIT(GPIO_BASE(GPIO_PORTC) + GPIOx_PUPDR_OFFSET, PUPDRy_1_BIT(8));							//PUPDR = 00 => No pull-up, pull-down
	SET_BIT(GPIO_BASE(GPIO_PORTC) + GPIOx_PUPDR_OFFSET, PUPDRy_0_BIT(8));
	WRITE_BITS(GPIO_BASE(GPIO_PORTC) + GPIOx_AFRH_OFFSET, AFRHy_3_BIT(8), AFRHy_0_BIT(8), 13);		//AF sel	dcmi	13

	SET_BIT(GPIO_BASE(GPIO_PORTC) + GPIOx_MODER_OFFSET, MODERy_1_BIT(9));							//MODER => 10
	CLEAR_BIT(GPIO_BASE(GPIO_PORTC) + GPIOx_MODER_OFFSET, MODERy_0_BIT(9));
	CLEAR_BIT(GPIO_BASE(GPIO_PORTC) + GPIOx_OTYPER_OFFSET, OTy_BIT(9));								//OT => 0
	SET_BIT(GPIO_BASE(GPIO_PORTC) + GPIOx_OSPEEDR_OFFSET, OSPEEDRy_1_BIT(9));						//OSPEEDR => 10
	CLEAR_BIT(GPIO_BASE(GPIO_PORTC) + GPIOx_OSPEEDR_OFFSET, OSPEEDRy_0_BIT(9));
	CLEAR_BIT(GPIO_BASE(GPIO_PORTC) + GPIOx_PUPDR_OFFSET, PUPDRy_1_BIT(9));							//PUPDR = 00 => No pull-up, pull-down
	SET_BIT(GPIO_BASE(GPIO_PORTC) + GPIOx_PUPDR_OFFSET, PUPDRy_0_BIT(9));
	WRITE_BITS(GPIO_BASE(GPIO_PORTC) + GPIOx_AFRH_OFFSET, AFRHy_3_BIT(9), AFRHy_0_BIT(9), 13);		//AF sel	dcmi	13

	SET_BIT(GPIO_BASE(GPIO_PORTE) + GPIOx_MODER_OFFSET, MODERy_1_BIT(4));							//MODER => 10
	CLEAR_BIT(GPIO_BASE(GPIO_PORTE) + GPIOx_MODER_OFFSET, MODERy_0_BIT(4));
	CLEAR_BIT(GPIO_BASE(GPIO_PORTE) + GPIOx_OTYPER_OFFSET, OTy_BIT(4));								//OT => 0
	SET_BIT(GPIO_BASE(GPIO_PORTE) + GPIOx_OSPEEDR_OFFSET, OSPEEDRy_1_BIT(4));						//OSPEEDR => 10
	CLEAR_BIT(GPIO_BASE(GPIO_PORTE) + GPIOx_OSPEEDR_OFFSET, OSPEEDRy_0_BIT(4));
	CLEAR_BIT(GPIO_BASE(GPIO_PORTE) + GPIOx_PUPDR_OFFSET, PUPDRy_1_BIT(4));							//PUPDR = 00 => No pull-up, pull-down
	SET_BIT(GPIO_BASE(GPIO_PORTE) + GPIOx_PUPDR_OFFSET, PUPDRy_0_BIT(4));
	WRITE_BITS(GPIO_BASE(GPIO_PORTE) + GPIOx_AFRL_OFFSET, AFRLy_3_BIT(4), AFRLy_0_BIT(4), 13);		//AF sel	dcmi	13

	SET_BIT(GPIO_BASE(GPIO_PORTE) + GPIOx_MODER_OFFSET, MODERy_1_BIT(5));							//MODER => 10
	CLEAR_BIT(GPIO_BASE(GPIO_PORTE) + GPIOx_MODER_OFFSET, MODERy_0_BIT(5));
	CLEAR_BIT(GPIO_BASE(GPIO_PORTE) + GPIOx_OTYPER_OFFSET, OTy_BIT(5));								//OT => 0
	SET_BIT(GPIO_BASE(GPIO_PORTE) + GPIOx_OSPEEDR_OFFSET, OSPEEDRy_1_BIT(5));						//OSPEEDR => 10
	CLEAR_BIT(GPIO_BASE(GPIO_PORTE) + GPIOx_OSPEEDR_OFFSET, OSPEEDRy_0_BIT(5));
	CLEAR_BIT(GPIO_BASE(GPIO_PORTE) + GPIOx_PUPDR_OFFSET, PUPDRy_1_BIT(5));							//PUPDR = 00 => No pull-up, pull-down
	SET_BIT(GPIO_BASE(GPIO_PORTE) + GPIOx_PUPDR_OFFSET, PUPDRy_0_BIT(5));
	WRITE_BITS(GPIO_BASE(GPIO_PORTE) + GPIOx_AFRL_OFFSET, AFRLy_3_BIT(5), AFRLy_0_BIT(5), 13);		//AF sel	dcmi	13

	SET_BIT(GPIO_BASE(GPIO_PORTE) + GPIOx_MODER_OFFSET, MODERy_1_BIT(6));							//MODER => 10
	CLEAR_BIT(GPIO_BASE(GPIO_PORTE) + GPIOx_MODER_OFFSET, MODERy_0_BIT(6));
	CLEAR_BIT(GPIO_BASE(GPIO_PORTE) + GPIOx_OTYPER_OFFSET, OTy_BIT(6));								//OT => 0
	SET_BIT(GPIO_BASE(GPIO_PORTE) + GPIOx_OSPEEDR_OFFSET, OSPEEDRy_1_BIT(6));						//OSPEEDR => 10
	CLEAR_BIT(GPIO_BASE(GPIO_PORTE) + GPIOx_OSPEEDR_OFFSET, OSPEEDRy_0_BIT(6));
	CLEAR_BIT(GPIO_BASE(GPIO_PORTE) + GPIOx_PUPDR_OFFSET, PUPDRy_1_BIT(6));							//PUPDR = 00 => No pull-up, pull-down
	SET_BIT(GPIO_BASE(GPIO_PORTE) + GPIOx_PUPDR_OFFSET, PUPDRy_0_BIT(6));
	WRITE_BITS(GPIO_BASE(GPIO_PORTE) + GPIOx_AFRL_OFFSET, AFRLy_3_BIT(6), AFRLy_0_BIT(6), 13);		//AF sel	dcmi	13
	/*
  	GPIO_InitTypeDef GPIO_InitStructure;
	NVIC_InitTypeDef NVIC_InitStructure;

  	RCC_AHB1PeriphClockCmd(RCC_AHB1Periph_GPIOA|RCC_AHB1Periph_GPIOB|RCC_AHB1Periph_GPIOC|RCC_AHB1Periph_GPIOE, ENABLE);

	RCC_AHB2PeriphClockCmd(RCC_AHB2Periph_DCMI,ENABLE);//ʹ��DCMIʱ��

  	//PA4/6��ʼ������
  	GPIO_InitStructure.GPIO_Pin = GPIO_Pin_4|GPIO_Pin_6;//PA4/6   ���ù������� HSYNC PIXCLK
  	GPIO_InitStructure.GPIO_Mode = GPIO_Mode_AF; //���ù�������
  	GPIO_InitStructure.GPIO_OType = GPIO_OType_PP;//��������
  	GPIO_InitStructure.GPIO_Speed = GPIO_Speed_100MHz;//100MHz
  	GPIO_InitStructure.GPIO_PuPd = GPIO_PuPd_UP;//����
  	GPIO_Init(GPIOA, &GPIO_InitStructure);//��ʼ��

  	GPIO_InitStructure.GPIO_Pin = GPIO_Pin_7|GPIO_Pin_6;// PB6/7   ���ù������� VSYNC D5
  	GPIO_Init(GPIOB, &GPIO_InitStructure);//��ʼ��

  	GPIO_InitStructure.GPIO_Pin = GPIO_Pin_6|GPIO_Pin_7|GPIO_Pin_8|GPIO_Pin_9;//PC6/7/8/9 ���ù������� D0 D1 D2 D3
  	GPIO_Init(GPIOC, &GPIO_InitStructure);//��ʼ��

  	GPIO_InitStructure.GPIO_Pin = GPIO_Pin_4|GPIO_Pin_5|GPIO_Pin_6;//PE4/5/6  ���ù�������  D4 D6 D7
  	GPIO_Init(GPIOE, &GPIO_InitStructure);//��ʼ��

	GPIO_PinAFConfig(GPIOA,GPIO_PinSource4,GPIO_AF_DCMI); //PA4,AF13  DCMI_HSYNC
	GPIO_PinAFConfig(GPIOA,GPIO_PinSource6,GPIO_AF_DCMI); //PA6,AF13  DCMI_PCLK
 	GPIO_PinAFConfig(GPIOB,GPIO_PinSource7,GPIO_AF_DCMI); //PB7,AF13  DCMI_VSYNC
 	GPIO_PinAFConfig(GPIOC,GPIO_PinSource6,GPIO_AF_DCMI); //PC6,AF13  DCMI_D0
 	GPIO_PinAFConfig(GPIOC,GPIO_PinSource7,GPIO_AF_DCMI); //PC7,AF13  DCMI_D1
	GPIO_PinAFConfig(GPIOC,GPIO_PinSource8,GPIO_AF_DCMI); //PC8,AF13  DCMI_D2
	GPIO_PinAFConfig(GPIOC,GPIO_PinSource9,GPIO_AF_DCMI); //PC9,AF13  DCMI_D3
	GPIO_PinAFConfig(GPIOE,GPIO_PinSource4,GPIO_AF_DCMI); //PE4,AF13  DCMI_D4
	GPIO_PinAFConfig(GPIOB,GPIO_PinSource6,GPIO_AF_DCMI); //PB6,AF13  DCMI_D5
	GPIO_PinAFConfig(GPIOE,GPIO_PinSource5,GPIO_AF_DCMI); //PE5,AF13  DCMI_D6
	GPIO_PinAFConfig(GPIOE,GPIO_PinSource6,GPIO_AF_DCMI); //PE6,AF13  DCMI_D7
	*/
	DCMI_DeInit();//����ԭ��������
	DCMI_Init();
	/*
  	NVIC_InitStructure.NVIC_IRQChannel = DCMI_IRQn;
	NVIC_InitStructure.NVIC_IRQChannelPreemptionPriority=3;	//��ռ���ȼ�
	NVIC_InitStructure.NVIC_IRQChannelSubPriority =2;		//�����ȼ�
	NVIC_InitStructure.NVIC_IRQChannelCmd = ENABLE;			//IRQͨ��ʹ��
	NVIC_Init(&NVIC_InitStructure);	//����ָ���Ĳ�����ʼ��NVIC�Ĵ�����
	*/
	SET_BIT(NVIC_ISER_BASE + NVIC_ISERn_OFFSET(2), 14); //IRQ78
}

void DCMI_Start(void){
	//��ʼд��GRAM
	SET_BIT(DMA2_BASE + DMA_S1CR_OFFSET, DMA_EN_BIT);
	SET_BIT(DCMI_BASE + DCMI_CR_OFFSET, CAPTURE_BIT);
	/*
	DMA_Cmd(DMA2_Stream1, ENABLE);//����DMA2,Stream1
	DCMI_CaptureCmd(ENABLE);//DCMI����ʹ��
	*/
}

void DCMI_Stop(void){
	CLEAR_BIT(DCMI_BASE + DCMI_CR_OFFSET, CAPTURE_BIT);
	while(READ_BIT(DCMI_BASE + DCMI_CR_OFFSET, CAPTURE_BIT));
	CLEAR_BIT(DMA2_BASE + DMA_S1CR_OFFSET, DMA_EN_BIT);
	/*
  	DCMI_CaptureCmd(DISABLE);//DCMI����ʹ�ر�
	while(DCMI->CR&0X01);		//�ȴ���������
	DMA_Cmd(DMA2_Stream1,DISABLE);//�ر�DMA2,Stream1
	*/
}

void dcmi_handler(void){
	if(READ_BIT(DCMI_BASE + DCMI_MIS_OFFSET, LINE_MIS_BIT)){
		SET_BIT(DCMI_BASE + DCMI_ICR_OFFSET, LINE_ISC_BIT);
		ov_frame++;
	}

	if(READ_BIT(DCMI_BASE + DCMI_MIS_OFFSET, FRAME_MIS_BIT)){
		SET_BIT(DCMI_BASE + DCMI_ICR_OFFSET, FRAME_ISC_BIT);
	}

	if(READ_BIT(DCMI_BASE + DCMI_MIS_OFFSET, VSYNC_MIS_BIT)){
		SET_BIT(DCMI_BASE + DCMI_ICR_OFFSET, VSYNC_ISC_BIT);
	}


	/*
	if(DCMI_GetITStatus(DCMI_IT_LINE)==SET)//��������
	{
		DCMI_ClearITPendingBit(DCMI_IT_LINE);//�����ж�
		ov_frame++;
	}

	if(DCMI_GetITStatus(DCMI_IT_FRAME)==SET)//������֡
	{
		DCMI_ClearITPendingBit(DCMI_IT_FRAME);//�����ж�
	}

	if(DCMI_GetITStatus(DCMI_IT_VSYNC)==SET)//���񵽳�
	{
		DCMI_ClearITPendingBit(DCMI_IT_VSYNC);//�����ж�
	}
	*/
}

void DCMI_Set_Window(uint16_t sx,uint16_t sy,uint16_t width,uint16_t height){
	DCMI_Stop();
	SET_BIT(DMA2_BASE + DMA_S1CR_OFFSET, DMA_EN_BIT);
	SET_BIT(DCMI_BASE + DCMI_CR_OFFSET, CAPTURE_BIT);
	/*
	DCMI_Stop();
	DMA_Cmd(DMA2_Stream1,ENABLE);	//����DMA2,Stream1
	DCMI_CaptureCmd(ENABLE);//DCMI����ʹ��
	*/
}

void DMA2_Steam1_DeInit(){
	CLEAR_BIT(DMA2_BASE + DMA_S1CR_OFFSET, DMA_EN_BIT);
	REG(DMA2_BASE + DMA_S1CR_OFFSET) = 0;
	REG(DMA2_BASE + DMA_S1NDTR_OFFSET) = 0;
	REG(DMA2_BASE + DMA_S1PAR_OFFSET) = 0;
	REG(DMA2_BASE + DMA_S1M0AR_OFFSET) = 0;
	REG(DMA2_BASE + DMA_S1M1AR_OFFSET) = 0;
	REG(DMA2_BASE + DMA_S1FCR_OFFSET) = 0X00000021;
	REG(DMA2_BASE + DMA_LIFCR_OFFSET) = (0x3d << 6);
}

uint8_t DMA2_Steam1_GetCmdStatus(){
	volatile uint32_t ret = 0;
	ret = READ_BIT(DMA2_BASE + DMA_S1CR_OFFSET, DMA_EN_BIT);
	if(ret > 0)
		return 1;
	else
		return 0;
}

void DMA2_Steam1_Init(uint32_t DMA_Memory0BaseAddr,uint16_t DMA_BufferSize){
	uint32_t DIR = 0b00;
	uint32_t CIRC = 0b1;
	uint32_t PINC = 0b0;
	uint32_t MINC = 0b1;
	uint32_t MSIZE = 0b01;
	uint32_t PSIZE = 0b10;
	uint32_t PL = 0b10;
	uint32_t PBURST = 0b00;
	uint32_t MBURST =  0b00;
	uint32_t CHSEL = 0b001;
	uint32_t DMA_S1CR = 0;
	DMA_S1CR |= (DIR << DMA_DIR_0_BIT);
	DMA_S1CR |= (CIRC << DMA_CIRC_BIT);
	DMA_S1CR |= (PINC << DMA_PINC_BIT);
	DMA_S1CR |= (MINC << DMA_MINC_BIT);
	DMA_S1CR |= (MSIZE << DMA_MSIZE_0_BIT);
	DMA_S1CR |= (PSIZE << DMA_PSIZE_0_BIT);
	DMA_S1CR |= (PL << DMA_PL_0_BIT);
	DMA_S1CR |= (PBURST << DMA_PBURST_0_BIT);
	DMA_S1CR |= (MBURST << DMA_MBURST_0_BIT);
	DMA_S1CR |= (CHSEL << DMA_CHSEL_0_BIT);

	REG(DMA2_BASE + DMA_S1CR_OFFSET) = DMA_S1CR;

	CLEAR_BIT(DMA2_BASE + DMA_S1FCR_OFFSET, DMA_DMDIS_BIT);
	WRITE_BITS(DMA2_BASE + DMA_S1FCR_OFFSET, DMA_FTH_1_BIT, DMA_FTH_0_BIT, 0);
	WRITE_BITS(DMA2_BASE + DMA_S1FCR_OFFSET, DMA_FTH_1_BIT, DMA_FTH_0_BIT, 0b11);
	SET_BIT(DMA2_BASE + DMA_S1FCR_OFFSET, DMA_DMDIS_BIT);

	REG(DMA2_BASE + DMA_S1NDTR_OFFSET) = DMA_BufferSize;
	REG(DMA2_BASE + DMA_S1PAR_OFFSET) = (uint32_t)(DCMI_BASE + DCMI_DR_OFFSET);					//	???
	REG(DMA2_BASE + DMA_S1M0AR_OFFSET) = (uint32_t)DMA_Memory0BaseAddr;

	SET_BIT(DMA2_BASE + DMA_S1CR_OFFSET, DMA_TCIE_BIT);
}

void DCMI_DeInit(){
	REG(DCMI_BASE + DCMI_CR_OFFSET) = 0;
	REG(DCMI_BASE + DCMI_IER_OFFSET) = 0;
	REG(DCMI_BASE + DCMI_ICR_OFFSET) = 0x1F;
	REG(DCMI_BASE + DCMI_ESCR_OFFSET) = 0;
	REG(DCMI_BASE + DCMI_ESUR_OFFSET) = 0;
	REG(DCMI_BASE + DCMI_CWSTRT_OFFSET) = 0;
	REG(DCMI_BASE + DCMI_CWSIZE_OFFSET) = 0;
}

void DCMI_Init(){
	CLEAR_BIT(DCMI_BASE + DCMI_CR_OFFSET, ENABLE_BIT);
	CLEAR_BIT(DCMI_BASE + DCMI_CR_OFFSET, CAPTURE_BIT);
	REG(DCMI_BASE + DCMI_CR_OFFSET) = 0;
	/*
	DCMI_InitStructure.DCMI_CaptureMode = DCMI_CaptureMode_SnapShot;//����ģʽ DCMI_CaptureMode_SnapShot
	DCMI_InitStructure.DCMI_CaptureRate = DCMI_CaptureRate_All_Frame;//ȫ֡����
	DCMI_InitStructure.DCMI_ExtendedDataMode = DCMI_ExtendedDataMode_8b;//8λ���ݸ�ʽ
	DCMI_InitStructure.DCMI_HSPolarity = DCMI_HSPolarity_Low;//DCMI_HSPolarity_High;//HSYNC �͵�ƽ��Ч
	DCMI_InitStructure.DCMI_PCKPolarity = DCMI_PCKPolarity_Falling;//PCLK ��������Ч
	DCMI_InitStructure.DCMI_SynchroMode = DCMI_SynchroMode_Hardware;//Ӳ��ͬ��HSYNC,VSYNC
	DCMI_InitStructure.DCMI_VSPolarity = DCMI_VSPolarity_High;//VSYNC �͵�ƽ��Ч
	*/
	SET_BIT(DCMI_BASE + DCMI_CR_OFFSET, CM_BIT);
	WRITE_BITS(DCMI_BASE + DCMI_CR_OFFSET, FCRC_1_BIT, FCRC_0_BIT, 0);
	WRITE_BITS(DCMI_BASE + DCMI_CR_OFFSET, EDM_1_BIT, EDM_0_BIT, 0);
	CLEAR_BIT(DCMI_BASE + DCMI_CR_OFFSET, HSPOL_BIT);
	CLEAR_BIT(DCMI_BASE + DCMI_CR_OFFSET, PCKPOL_BIT);
	CLEAR_BIT(DCMI_BASE + DCMI_CR_OFFSET, ESS_BIT);
	SET_BIT(DCMI_BASE + DCMI_CR_OFFSET, VSPOL_BIT);

	SET_BIT(DCMI_BASE + DCMI_IER_OFFSET, FRAME_IE_BIT);
	SET_BIT(DCMI_BASE + DCMI_IER_OFFSET, LINE_IE_BIT);
	SET_BIT(DCMI_BASE + DCMI_ICR_OFFSET, VSYNC_ISC_BIT);
	SET_BIT(DCMI_BASE + DCMI_IER_OFFSET, VSPOL_BIT);

	SET_BIT(DCMI_BASE + DCMI_CR_OFFSET, ENABLE_BIT);
	/*
	DCMI_ITConfig(DCMI_IT_FRAME,ENABLE);//����֡�ж�
	DCMI_ITConfig(DCMI_IT_LINE,ENABLE); //�������ж�
	DCMI_ClearITPendingBit(DCMI_IT_VSYNC);
	DCMI_ITConfig(DCMI_IT_VSYNC,ENABLE); //�������ж�
	DCMI_Cmd(ENABLE);	//DCMIʹ��
	*/
}
